version: '3.8'

services:

  frontend:
    build: ./frontend
<<<<<<< HEAD
    ports:
      - "8081:80"
=======
    environment:
      PORT: ${PORT}
    ports:
      - "8080:80"
>>>>>>> production
    depends_on:
      - backend

  backend:
    build: ./backend
<<<<<<< HEAD
    env_file:
      - ./backend/.env
=======
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PWD: ${ADMIN_PWD}
>>>>>>> production
#    ports:
#      - "3001:3000" USELESS BC WE DONT CALL THE API FROM THE HOST
    depends_on:
      - db

  db:
    image: postgres:15
<<<<<<< HEAD
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_DB: my_library_test
=======
>>>>>>> production
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
