version: '3.8'

services:

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
#    ports:
#      - "3001:3000" USELESS BC WE DONT CALL THE API FROM THE HOST
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_DB: my_library_test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
